sudo: false
language: python
python:
  - 3.6
install: 
  - pip install pandas
  - pip install scipy
  - pip install PyQt5
addons:
 apt:
  packages:
    - libxkbcommon-x11-0
dist: xenial
services:
  - xvfb
script: 
- xvfb-run make test
- python -m unittest discover -s tests
