sudo: false
language: python
python:
  - 3.6
install: 
  - pip install pandas
  - pip install scipy
  - pip install PyQt5
before_install:
        - sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0
        - sudo apt install libxkbcommon-x11-0
dist: xenial
services:
  - xvfb
script: 
- python -m unittest discover -s tests
