sudo: false
language: python
python:
  - 3.6
install: 
  - pip install pandas
  - pip install scipy
  - pip install PyQt5
script: 
- python -m unittest discover -s tests
dist: xenial
services:
  - xvfb