sudo: false
language: python
python:
  - 3.6
install: 
  - pip install pandas
  - pip install scipy
  - pip install PyQt5
before_install:
        - sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0
        - sudo apt install libxkbcommon-x11-0
services: xvfb
dist: xenial

script: 
- pip install pytest pytest-qt
- python -m unittest discover tests
#- python -m unittest discover -s tests
